image: 'rust:latest'

stages:
  - build
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
before_script:
  - apt-get update -qq
  - apt-get install -qq build-essential curl git

build:redox:
  image: "redoxos/redoxer"
  stage: build
  script:
    - redoxer build --verbose
  cache:
    paths:
      - cargo/
      - target/

build:linux:
  stage: build
  script:
    - cargo build
  cache:
    paths:
      - cargo/
      - target/

build:web:
  stage: build
  before_script:
    - cargo install --force cargo-web
  script:
    - cargo web build
  cache:
    paths:
      - cargo/
      - target/

test:linux:
  stage: test
  before_script:
    - apt-get update && apt-get -y install cmake
    - apt-get install libsdl2-dev -y
  dependencies:
    - build:linux
  script:
    - rustup default nightly
    - cargo test
