[package]
name = "orbtk-widgets"
version = "0.3.0-alpha1"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Base OrbTk widget library."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["ui", "widgets"]
edition = "2018"

[dependencies]
dces = "0.2"
orbtk-api = "0.3.0-alpha1"
orbtk-shell = "0.3.0-alpha1"
orbtk-theme = "0.3.0-alpha1"
orbtk-render = "0.3.0-alpha1"
orbtk-utils = "0.3.0-alpha1"