[package]
name = "orbtk-shell"
version = "0.3.0-alpha1"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Window shell crate used by OrbTk."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["shell", "window", "ui"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.20"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
spin_sleep = "0.3.7"
image = "0.22.3"

[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "redox")))'.dependencies]
minifb = "0.13"
# minifb = { git = "https://github.com/emoon/rust_minifb.git" }

# [target.'cfg(target_os = "redox")'.dependencies]
# minifb-fix = { git = "https://github.com/FloVanGH/rust_minifb", branch = "redox_unix" }

[dependencies]
orbtk-render = "0.3.0-alpha1"
orbtk-utils = "0.3.0-alpha1"
lazy_static = "1.4.0"